### ISSUE TITLE
Error when running ‘Omniglot.py'

### ISSUE THREAD

**Issue by ghost** [llSourcell/How-to-Learn-from-Little-Data#5] opened 2017-05-14 14:49 UTC
I was testing the code using tensorflow 1.0 , but encounter the following error message:

```
Traceback (most recent call last):
  File "Omniglot.py", line 112, in <module>
    omniglot()
  File "Omniglot.py", line 31, in omniglot
    output_var, output_var_flatten, params = memory_augmented_neural_network(input_ph, target_ph, batch_size=batch_size, nb_class=nb_class, memory_shape=memory_shape, controller_size=controller_size, input_size=input_size, nb_reads=nb_reads)
  File "/Users/home/How-to-Learn-from-Little-Data/MANN/Model.py", line 33, in memory_augmented_neural_network
    W_key = tf.get_variable('W_key', shape=shape,initializer=tf.random_uniform_initializer(-1*high, high))
  File "/Users/home/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/Users/home/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/Users/home/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/Users/home/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 287, in _true_getter
    is_scalar = shape is not None and not shape
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

I haven’t  figure out how to fix it, anyone has an idea?

**Comment by AdamMayToString** [comment] 2017-05-15 00:13
I hope you're aware the code isn't intended for TF 1.0, it's intended for 0.12, so you're going to get weird bugs like this. I got this error, but I didn't realize that.

**Comment by ghost** [comment] 2017-05-15 06:31
Yes I do aware that,  I still wish to get it run on TF1.0 , but currently can't figure out how, the error message seems like coming from Numpy,  which is wired.

**Comment by sino30535** [comment] 2017-05-18 18:21
The error was caused by shape argument in tf.get_variable. The shape you assign to shape argument is a numpy array, which cannot be evaluated in boolean context. You can get this error message if you try:
x = np.array((1,2,3))
not x
The easy solution to this problem is just pass the shape argument in tuples, like
shape = (nb_reads, controller_size, memory_shape[1]), same to other tf.get_variable.

**Comment by ghost** [comment] 2017-05-19 08:57
That solves the problem! Thank you!

**Closed as completed** 2017-05-19 08:57 UTC
